name: sunH0 workflow

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop, feature/*]
    paths-ignore:
      - "doc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.SH0_DOCKERHUB_USERNAME}}
          password: ${{secrets.SH0_DOCKERHUB_TOKEN}}
          
      # 도커 이미지 빌드 및 push   
      - name: build and release to DockerHub
        env:
          NAME: sunh072010 # DockerHub 계정 명
          REPO: deploy-test #  DockerHub 레포 이름
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
